/*++ BUILD Version: 0001    // Increment this if a change has global effects

Copyright (c) 1992  Microsoft Corporation

Module Name:

    wlevents.h

Abstract:

    Definitions for User Profiles Events

Author:

    Johannec 12-08-93

Revision History:

Notes:

    This file is generated by the MC tool from the wlevents.mc file.

--*/


#ifndef _PROFEVT_
#define _PROFEVT_


/////////////////////////////////////////////////////////////////////////
//
// Winlogon Events (1000 - 1999)
//
/////////////////////////////////////////////////////////////////////////

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//
#define STATUS_SEVERITY_WARNING          0x2
#define STATUS_SEVERITY_SUCCESS          0x0
#define STATUS_SEVERITY_INFORMATIONAL    0x1
#define STATUS_SEVERITY_ERROR            0x3


//
// MessageId: EVENT_SET_HOME_DIRECTORY_FAILED
//
// MessageText:
//
//  Failed to set the user's home directory %1.
//
#define EVENT_SET_HOME_DIRECTORY_FAILED  0xC00003E8L

//
// MessageId: EVENT_AUTOCHK_DATA
//
// MessageText:
//
//  %1
//
#define EVENT_AUTOCHK_DATA               0x400003E9L

//
// MessageId: EVENT_SHELL_RESTARTED
//
// MessageText:
//
//  The shell stopped unexpectedly and %1 was restarted.
//
#define EVENT_SHELL_RESTARTED            0x400003EAL


#endif // _PROFEVT_

