/*++

Copyright (c) 1996 Microsoft Corporation

Module Name:

    msg.h

Abstract:

    This module contains the definition sprestrt messages.

Author:

    Ted Miller (tedm) Feb 1996.

Revision History:

Notes:

    This file is generated by the message compiler from msg.mc.

--*/

#ifndef _SPRESTRT_
#define _SPRESTRT_

//
//  Values are 32 bit values layed out as follows:
//
//   3 3 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1
//   1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0
//  +---+-+-+-----------------------+-------------------------------+
//  |Sev|C|R|     Facility          |               Code            |
//  +---+-+-+-----------------------+-------------------------------+
//
//  where
//
//      Sev - is the severity code
//
//          00 - Success
//          01 - Informational
//          10 - Warning
//          11 - Error
//
//      C - is the Customer code flag
//
//      R - is a reserved bit
//
//      Facility - is the facility code
//
//      Code - is the facility's status code
//
//
// Define the facility codes
//


//
// Define the severity codes
//


//
// MessageId: MSG_CRLF
//
// MessageText:
//
//  
//
#define MSG_CRLF                         ((ULONG)0x00000001L)

#endif // _SPRESTRT_
