/****************************** Module Header ******************************\
* Module Name: KBDBR.H
*
* keyboard layout header for Brazilian
*
* Copyright (c) 1985-95, Microsoft Corporation
*
* Various defines for use by keyboard input code.
*
* History:
*
* created by KBDTOOL Sun Mar 15 00:58:09 2020
*
\***************************************************************************/

/*
 * kbd.h is for the USA.  There are no values to be overridden.
*/
#include "kbd.h"

